### PR TITLE
Bug: fixed broken image in user logo

### PR DESCRIPTION
**Pull request by Febin-Joseph**
Hi ,
    i have found a Bug after user login using vercel account,  the Bug is :

- If the user doesn't have a Profile image and a name in vercel account then it will show a broken image in Header   in the part of    the users logo like this:
  **Before Image :**

no-image

**Fixed image :**
Now if the user doesn't have a profile image and name in vercel the default icon will be displayed else if having a profile image and doesn't have a name then only the profile image will be dispalyed as before.

icon

### CODE REVIEW

**Comment by shadcn** [comment]
I wonder if we can instead use the [`avatar`](https://ui.shadcn.com/docs/components/avatar) component with `<AvatarFallback />` instead?


```tsx
<Avatar>
  <AvatarImage src="https://github.com/shadcn.png" />
  <AvatarFallback>CN</AvatarFallback>
</Avatar>
```

**Comment by Febin-Joseph** [comment]
@shadcn But in the place of CN text in here `<AvatarFallback>CN</AvatarFallback>` what can be given.

**Comment by shadcn** [comment]
@Febin-Joseph We can use the user initials. See https://github.com/vercel/ai-chatbot/blob/69ca8fcc22bd180fdb393c45968994a4ea654327/components/user-menu.tsx#L21

**Comment by Febin-Joseph** [comment]
@shadcn The case is if the user doesn't have a profile pic and also doesn't have a user name in their vercel account then only the broken image will be displayed and think if the user have a username in vercel account but doesn't have a profile pic, in that scenario instead of the broken image the user's names two letters will be displayed in the place of profile.

**But in this case the user doesn't have a name too.**  then how can use `getUserInitials()`

**Pull request closed without merging**
