### PR TITLE
Create demo using gemini model

### PR DESCRIPTION
**Pull request by jeremyphilemon**
### Gemini Function Calling Feedback

- the model has a strict order for multi turn chat completions:
    - user → model: call function → function response → model → user
- as a result, if we choose to include the function call + response, we have to do a model generation after rendering a component, which is another recursive call.
- it would be great to handle function calls by the client without requiring another model generation, or just offer more flexibility without the order as constraints
- if we choose to remove the function call + response, the model has no memory about the interaction and messes with the sequential calls, so it requires some careful prompt injection to let the model know what has happened
- also there can't be consecutive model roles, so we can't append multiple ui interactions to the conversation history as distinct messages
- vision and text models do not follow the same `messages` input parameter format
- when using tools, the model does not answer to general questions
    - user: who is michael jordan?
    - model: I cannot fulfill this request. I do not have the functionality to provide information about people.
- System message support would be very useful
- Being able to force the call of a specific function would be useful (for generateObject and streamObject)
- From the docs it’s unclear if the tool call arguments are streamed with deltas
- Support for a ‘seed’ parameter would be great
- Support for JSON mode (or grammars) would be great
- Temperature parameter (ranging from 0 to infinity) is difficult to map on our temperature range 0…1
- For parallel calls, there is no clear mapping from functionCall to functionResponse (e.g. via a call id)

### CODE REVIEW

**Comment by Godrules500** [comment]
Can this work with the new streamUI from AI sdk 3.1?

**Comment by athrael-soju** [comment]
@Godrules500 I'd advice holding up, because the new AI SDK came with a few issues.

**Comment by Godrules500** [comment]
> @Godrules500 I'd advice holding up, because the new AI SDK came with a few issues.

Bummer! Do you know what kind of issues off the top of your head?  Also, wish there was a VertexAI implementation since I'm technically not allowed to use the google ai wrapper

**Comment by athrael-soju** [comment]
> > @Godrules500 I'd advice holding up, because the new AI SDK came with a few issues.
> 
> Bummer! Do you know what kind of issues off the top of your head? Also, wish there was a VertexAI implementation since I'm technically not allowed to use the google ai wrapper

This should give you an idea :) https://github.com/vercel/ai-chatbot/issues/325
Looks like it's a @vercel/ai related issue affecting several templates.

**Pull request closed without merging**
